In [1]:
import pandas as pd

import warnings
warnings.simplefilter('ignore')

In [2]:
# importing the dataset.

df = pd.read_csv(r'clean.csv')
df

       Age  Heart_Rate  Calories  Gender_male
0       68       105.0     231.0            1
1       20        94.0      66.0            0
2       69        88.0      26.0            1
3       34       100.0      71.0            0
4       27        81.0      35.0            0
...    ...         ...       ...          ...
14995   20        92.0      45.0            0
14996   27        85.0      23.0            0
14997   43        90.0      75.0            0
14998   78        84.0      11.0            1
14999   63        92.0      98.0            1

[15000 rows x 4 columns]

In [3]:
# Seperating the Dependent and Independent variables.

X = df.drop(columns=['Calories'])
y = df['Calories']

In [4]:
# Splitting the data into Train and Test

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,y,random_state=42,train_size=0.8)

In [10]:
# creating the model

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# Preprocessing the train data by increasing to degree of 3
poly_convt = PolynomialFeatures(degree=3)
x_train_poly = pd.DataFrame(poly_convt.fit_transform(x_train))

#  Modelling the Train data
model = LinearRegression()
model.fit(x_train_poly,y_train)

# Predicting on train data
ypred_train = model.predict(x_train_poly)

# Calculating the train r2 score and Cross Validation Score
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

print('Train r2 score is :',r2_score(y_train,ypred_train))
print('Cross validation score is :',cross_val_score(model,x_train,y_train,cv=5).mean())

# Preprocessing the test data by increasing to degree of 3
x_test_poly = pd.DataFrame(poly_convt.transform(x_test))

# Predicting on Test data
ypred_test = model.predict(x_test_poly)

# Calculating the test r2 score
print('Test r2 score is :',r2_score(y_test,ypred_test))

Train r2 score is : 0.8660967254417152
Cross validation score is : 0.8253414765235016
Test r2 score is : 0.8724614529882481